LEC=/lymon/homes/cs494/notes/Jgraph

copy:
	cp $(LEC)/axis.jgr .
	cp $(LEC)/axis.ps .
	cp $(LEC)/bar.jgr .
	cp $(LEC)/copygraph.jgr .
	cp $(LEC)/copygraph.ps .
	cp $(LEC)/curve.jgr .
	cp $(LEC)/curve.ps .
	cp $(LEC)/fbf.jgr .
	cp $(LEC)/fbf.ps .
	cp $(LEC)/football.eps .
	cp $(LEC)/football.jgr .
	cp $(LEC)/football.ps .
	cp $(LEC)/hlabels.jgr .
	cp $(LEC)/hlabels.ps .
	cp $(LEC)/legend1.jgr .
	cp $(LEC)/legend1.ps .
	cp $(LEC)/legend2.jgr .
	cp $(LEC)/legend2.ps .
	cp $(LEC)/poly.jgr .
	cp $(LEC)/poly.ps .
	cp $(LEC)/simp1.jgr .
	cp $(LEC)/simp1.ps .
	cp $(LEC)/simp2.jgr .
	cp $(LEC)/simp2.ps .
	cp $(LEC)/strings.jgr .
	cp $(LEC)/strings.ps .
